import type { CountryCode } from './server/prisma'

export interface Region {
  code: CountryCode
  name: string
  color: string
  requirements: string[]
  flag: string
  lat: number
  lng: number
}

export const REGIONS = [
  {
    code: 'US',
    name: 'United States',
    color: '#3B82F6',
    requirements: [
      'Net quantity of contents (both metric and inch/pound units)',
      'Identity of commodity',
      'Name and place of business of manufacturer/packer/distributor',
      'Compliance with Fair Packaging and Labeling Act (FPLA)',
      'UPC barcode (standard industry practice)',
      'FDA/FTC specific compliance (dependent on product type)',
      'English required (primary language)',
    ],
    flag: '🇺🇸',
    lat: 37.0902,
    lng: -95.7129,
  },
  {
    code: 'EU',
    name: 'European Union',
    color: '#6366F1',
    requirements: [
      'CE marking (for applicable products)',
      'EU Declaration of Conformity (DoC)',
      'Name and contact of EU Authorized Representative/Importer',
      'Allergens in bold (for food/cosmetics)',
      'Metric units',
      'Multilingual labeling (local language(s) required by member state)',
      'WEEE symbol (for electrical/electronic equipment)',
    ],
    flag: '🇪🇺',
    lat: 54.526,
    lng: 15.2551,
  },
  {
    code: 'UK',
    name: 'United Kingdom',
    color: '#EF4444',
    requirements: [
      'UKCA marking (required for Great Britain, though CE mark acceptance is extended for most goods)',
      'UK importer/responsible person information (for Great Britain)',
      'CE marking (required for Northern Ireland; acceptable in Great Britain for most goods)',
      'Recycling symbols (e.g., Mobius loop)',
      'Metric units',
    ],
    flag: '🇬🇧',
    lat: 55.3781,
    lng: -3.436,
  },
  {
    code: 'JP',
    name: 'Japan',
    color: '#F43F5E',
    requirements: [
      'Labeling in Japanese (must be affixed by importer before sale)',
      'Country of origin',
      'JIS standards compliance (for certain industrial products)',
      'JAN barcode (standard industry practice)',
      'Household Goods Quality Labeling Act (for consumer goods)',
      'Electrical Appliance and Material Safety Law (PSE Mark for electrical products)',
    ],
    flag: '🇯🇵',
    lat: 36.2048,
    lng: 138.2529,
  },
  {
    code: 'CN',
    name: 'China',
    color: '#F59E0B',
    requirements: [
      'CCC mark (China Compulsory Certification) for designated products',
      'Labeling in Simplified Mandarin Chinese',
      'GB Standards compliance (Guobiao standards)',
      'Manufacturer/importer details',
      'Specific claims rules (e.g., on health or environmental claims)',
    ],
    flag: '🇨🇳',
    lat: 35.8617,
    lng: 104.1954,
  },
  {
    code: 'KR',
    name: 'South Korea',
    color: '#10B981',
    requirements: [
      'KC mark (Korea Certification) for electrical/electronic goods',
      'Korean labeling (required information: model, rating, date of manufacture, etc.)',
      'Country of origin',
      'Local representative required (for KC certification)',
      'Compliance with Korean Safety and Quality Standards',
    ],
    flag: '🇰🇷',
    lat: 35.9078,
    lng: 127.7669,
  },
  {
    code: 'BR',
    name: 'Brazil',
    color: '#22C55E',
    requirements: [
      'INMETRO certification/seal (for mandatory product categories like electrical, automotive components, etc.)',
      'Labeling in Portuguese (must include essential consumer information)',
      'ANVISA registration/compliance (for health products: food, cosmetics, medical devices)',
      'Name and address of Brazilian manufacturer/importer',
      'Metric units',
    ],
    flag: '🇧🇷',
    lat: -14.235,
    lng: -51.9253,
  },
  {
    code: 'AU',
    name: 'Australia',
    color: '#8B5CF6',
    requirements: [
      'Compliance with Australian Consumer Law (ACL)',
      'Accurate country of origin claims (mandatory for most food)',
      'Importer details (for pre-packaged goods)',
      'Metric units (Trade Measurement Laws)',
      'Specific labeling for safety warnings, chemicals, and therapeutic goods (TGA)',
      'Energy Rating Label/WELS (for applicable appliances)',
    ],
    flag: '🇦🇺',
    lat: -25.2744,
    lng: 133.7751,
  },
  {
    code: 'CA',
    name: 'Canada',
    color: '#DC2626',
    requirements: [
      'Bilingual labeling (English and French)',
      'Net quantity declaration (metric units required)',
      'Common name of product',
      'Dealer name and principal place of business',
      'Country of origin',
      'Compliance with Consumer Packaging and Labelling Act (CPLA)',
    ],
    flag: '🇨🇦',
    lat: 56.1304,
    lng: -106.3468,
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    color: '#0EA5E9',
    requirements: [
      'Country of origin labeling',
      'Metric units',
      'Food Standards Australia New Zealand (FSANZ) compliance',
      'Product safety standards compliance',
      'Supplier identification',
    ],
    flag: '🇳🇿',
    lat: -40.9006,
    lng: 174.886,
  },
  {
    code: 'SG',
    name: 'Singapore',
    color: '#E11D48',
    requirements: [
      'Labeling in English',
      'Country of origin',
      'Net content/quantity',
      'Safety Mark (for controlled goods)',
      'Importer/local distributor details',
    ],
    flag: '🇸🇬',
    lat: 1.3521,
    lng: 103.8198,
  },
  {
    code: 'HK',
    name: 'Hong Kong',
    color: '#F97316',
    requirements: [
      'Bilingual labeling (English and Traditional Chinese)',
      'Product name and description',
      'Country of origin',
      'Net weight/volume',
      'Manufacturer/importer information',
    ],
    flag: '🇭🇰',
    lat: 22.3193,
    lng: 114.1694,
  },
] as const satisfies Region[]
